fix(config): add descriptions to JSON schema properties
ubiquity-os-marketplace/text-vector-embeddings pull request #49
Opened 2024-11-26 12:48 UTC by Keyrxng

Relates to https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/24

2024-11-29 13:23 UTC, gentlementlegen approved these changes

2024-11-30 05:53 UTC, gentlementlegen commented
@Keyrxng maybe you should add examples too?

2024-12-04 07:59 UTC, rndquu requested changes
@Keyrxng Could you: 
1. Add examples 
2. Fix code conflicts
3. [Fix prettier](https://github.com/ubiquity-os-marketplace/command-ask/pull/41#pullrequestreview-2477647265)

2024-12-20 09:12 UTC, Keyrxng commented
This shouldn't have been closed. 

https://github.com/ubiquity-os-marketplace/text-vector-embeddings/issues/48

Can't move til this issue is resolved. I commented elsewhere that not all props need examples because the HTML input ele contains the value already.

2024-12-20 09:33 UTC, rndquu commented
> Can't move til [this](https://github.com/ubiquity-os-marketplace/text-vector-embeddings/issues/48) issue is resolved

https://github.com/ubiquity-os-marketplace/text-vector-embeddings/issues/48 is not connected with https://github.com/ubiquity-os-marketplace/text-vector-embeddings/pull/49#pullrequestreview-2477585167

2024-12-20 09:37 UTC, Keyrxng commented
> > Can't move til [this](https://github.com/ubiquity-os-marketplace/text-vector-embeddings/issues/48) issue is resolved
> 
> #48 is not connected with [#49 (review)](https://github.com/ubiquity-os-marketplace/text-vector-embeddings/pull/49#pullrequestreview-2477585167)

There is no description because it is not (at the time) used within the code base, so it is sort of related.

I can review this plugin's code and check again but my issues are being ignored so little point in that 

```ts
"warningThreshold": {
        "default": 0.75,
        "description": "",
        "type": "number"
      },

```

2025-02-05 04:50 UTC, gentlementlegen commented
@Keyrxng Can we reopen and merge this in?

2025-02-05 04:54 UTC, Keyrxng commented
A quick scan over the current codebase compared to my comment above 3 months ago shows the `warningThreshold` being used in the codebase now, so I'm able to update that with a description and we can merge it in if it's accurate.

If you re-open, I'll make the change mate cheers.

2025-02-05 05:13 UTC, Keyrxng commented
I'm not confident the descriptions are accurate - @shiv810 any suggestions would be appreciated.

2025-02-05 06:59 UTC, rndquu approved these changes

2025-02-07 13:56 UTC, merged